/*
AUTO-GENERATED by sysplugin-prepare on every prep run.

Snapshot of the plugin's root main.go (or main_mono.go) at generation time:
  - package renamed to "system"
  - func main() stripped (illegal in a non-main package)
  - //go:build tag PRESERVED so this file is selected under the same build
    tag as its source

DO NOT EDIT. Always regenerated when the source differs (content-aware-skip).
Edit the corresponding root main.go or main_mono.go instead. Any direct
edits here will be silently overwritten on the next sysplugin-prepare run.

Plugins with helpers split across multiple root .go files (e.g. init.go) must
move those helpers into this system/ subpackage by hand — the generator only
snapshots main.go and main_mono.go.
*/

//go:build !mono

package system

import (
	sdkapi "sdk/api"

	"com.flarego.wired-coinslot/src"
)

// Init must return error: the core plugin loader only invokes Init when it
// type-asserts to func(sdkapi.IPluginApi) error (see core plugin-init.go). A
// no-return Init is silently skipped, so the plugin never registers anything.
func Init(api sdkapi.IPluginApi) error {
	// Ensure a default coinslot config exists.
	src.InitWiredCoinslots(api)

	// Portal + admin routes and navigation.
	src.SetRoutes(api)
	src.SetAdminRoutes(api)
	src.SetAdminNavs(api)

	// Start the GPIO agents, pulse counters and payment session manager.
	src.StartManager(api)

	// Register the payment provider so coinslots appear as a payment option.
	provider := src.NewPaymentProvider(api)
	api.Payments().NewPaymentProvider(provider)

	return nil
}
